### PR TITLE
Beginning reimplementation of User entity.

### PR DESCRIPTION
**Pull request by jdickey**
Per Issue #54 and Issue #240, pulling back from  "unbuilt Gem" into main app, applying lessons learnt
along the way.

### CODE REVIEW

**Comment by jdickey** [comment]
The latest commit message includes the bit

> Next up is a last bit of cleanup, implementing the pattern demonstrated
by the `ProfileFormatterSetup` class to add attributes *from*
`#initialize` that are *unknown to* `#initialize`.

That class [`ProfileFormatterSetup`](https://github.com/jdickey/new_poc/blob/7c5620d/app/entities/user/profile_formatter_setup.rb) demonstrates some useful [metaprogramming](https://github.com/chelseakomlo/gschool-blog/blob/master/source/2013-02-23-ruby-metaprogramming-an-example.html.markdown) chops, it's not simply a copy-and-paste model for the other non-core attributes presently added to the `User` class in its [`#initialize`](https://github.com/jdickey/new_poc/blob/7c5620d/app/entities/user.rb#L37-L44) method.

Or, at least as likely, the current implementations are flawed. Consider the [`PersistenceStatus`](https://github.com/jdickey/new_poc/blob/7c5620d/app/entities/user/persistence_status.rb) class, to which `User` [delegates](https://github.com/jdickey/new_poc/blob/7c5620d/app/entities/user.rb#L22) the `#persisted?` query method and `slug` attribute reader.

If the `User` class knows *that much* about its instance of `PersistenceStatus`, then why bother having the latter in the first place?  The delegation should happen *within* the `PersistenceStatus` class itself, acting on its containing (really, at that point merely *invoking) entity.

That *seems* to make sense. Check back shortly to see how closely practice tracks optimistic theory.

**Comment by jdickey** [comment]
So why is the last commit (actually last three commits) "minimally satisfactory refactoring"?

Quoting from [that commit's commit message](https://github.com/jdickey/new_poc/commit/0f58f43):

> It still adds state (an instance variable) to the User entity rather
than simply modifying behaviour, but then again, so does the
`ProfileFormatterSetup` immediately following that call, and I didn't
spin my gears all day writing *that*. (In my own defence, the latter
*is* understandably short and clear.)

Quoting from [a comment](https://github.com/jdickey/new_poc/blob/0f58f43/app/entities/user/validator_support.rb#L60-L65) introducing [`Entity::User::ValidatorSupport.setup](https://github.com/jdickey/new_poc/blob/0f58f43/app/entities/user/validator_support.rb#L66-L69):

> Why does this particularly suck? Because now I have to add an *instance variable* to the underlying entity, instead of just using standard Ruby metaprogramming to have my way with including modules, adding validations, and such. I've long felt that adding state to an object (which is what instance variables *are*) is inferior to modifying its logic via `extend` and other bits of Ruby inheritance/metaprogramming.

:unamused:

**Comment by jdickey** [comment]
*Right*. As of Commit 7a78602, we have the `User` entity (and supporting code) with API functionality matching [`Newpoc::Entity::User`](https://github.com/jdickey/new_poc/tree/7a78602/lib/newpoc-entity-user). Once we replace its use in the controller actions, repository, factory, etc., with `Entity::User`, we can delete that unbuilt Gem from `lib`.

Sounds like a plan, but remember [von Moltke](https://en.wikiquote.org/wiki/Helmuth_von_Moltke_the_Elder#Sourced).

**Comment by jdickey** [comment]
As noted in the commit message for Commit d0ca00b, we're back on the horns of "when and how do we filter what `#attributes` hands back to us", to avoid, say, looking for DAO fields for `markdown_converter` or `:validator`?

State, particularly state *unrelated to core domain attributes of an object*, is *evil*. Up to now, we've been using the `attributes` hash of our entities (which is intentionally an analogue to the `#attributes` method of [ActiveRecord](http://apidock.com/rails/ActiveRecord/AttributeMethods/attributes)) as a convenient, if lazy, way to access things like the Markdown-to-HTML converter or suchlike. That's the real code stench our specs are patiently beating us about the head with, and rigging Ruby Goldbergs every time we run across them is *not* the answer. :-1:

**Comment by jdickey** [comment]
In line with the preceding comment, the following thoughts:

1. When I talk about "entity classes" here, unless otherwise specified, I'm talking about the newest form of the [`Entity::User` class](https://github.com/jdickey/new_poc/tree/d0ca00b/app/entities/user.rb) and its [mixins](https://github.com/jdickey/new_poc/tree/d0ca00b/app/entities/user), since no `Post` or `Session` entities yet exist in this implementation;
1. When talking about "attributes" or "properties" (the terms here *are not* interchangeable, as I'll discuss below), it is irrelevant to the outside code whether those are implemented as a concrete data structure (such as a `Hash`), a class instance that can be accessed *as though it were* such a data structure (think of Rails' [`HashWithIndifferentAccess`](http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html) or Tom Chapin's [FancyOpenStruct](https://github.com/tomchapin/fancy-open-struct) as examples), or a method returning either of the preceding.

Now, the real point.

> The `attributes` method for an entity presently simply returns a `Hash` of all *instance variables* defined for that entity instance; the subscript (`:[]`) operator is aliased to that, and the various [classes and modules](https://github.com/jdickey/new_poc/tree/d0ca00b/app/entities/user) which manipulate the entity instance add instance variables directly to the class.

In hindsight, this last is exactly backwards, and has been so since first implemented. Rather, a better scheme would see:

1. An `#attributes` method returns a `Hash` of *core attributes*, an `#[]` method returns a single entry *from that set of core attributes*. Core attributes are  conceptually bound to the entity in question (such as a "name" or "profile" for a User entity);
1. *Properties* are, generically, instances of supporting classes that perform tasks for the class. The Markdown-to-HTML converter class instance bound to the entity instance is a property. Properties *are not* included in the collection returned by `#attributes`, and thus, none of the ad-hoc filtering that has been heretofore endemic is necessary. When you're comparing two entities, for example, you would compare their `#attributes` return values. Simple as that;
1. Properties, being support-class instances, *are not* ordinarily exposed through an entity class' public API via `attr_reader`. There may be an `attr_writer` for setting the property instance (e.g., for tests). A preferred idiom would be to have an internal class that provides a writer (and possibly reader) for such a property on its container. This class would have an easily identifiable name (e.g., `Entity::User::ConverterPropertyAccessor`) that would make it easy to `grep`, either manually or via a pre-commit hook.

Thoughts? Anything I'm forgetting?

**Comment by jdickey** [comment]
The "obvious quick fix" to this would be simply to replace the existing [`#attributes`](https://github.com/jdickey/new_poc/blob/d0ca00b/app/entities/user/core_attribute_setup/internals.rb#L25-L27) implementation with one that explicitly builds a `Hash` (or equivalent) with explicit items, either by selectively white- or blacklisting `instance_values` entries.

Is that *good enough* and *fast enough* to overcome the new SRP violation? Or is there a better way, sufficiently easy/quick to be practical while at the same time not duplicating or replacing the work that has gone (recently) before?

Sure there is, and it's clued in by the fact that every single attribute that we want to treat *as* an attribute has the equivalent of the code `entity.class_eval { attr_reader :the_attribute }`. Attributes, instead of making that call, should instead call a (new) method we mix in to the entity, tentatively named `#add_attribute`. Here's what it might look like:

```ruby
        entity.define_singleton_method :add_attribute do |attribute, value|
          class_eval { attr_reader attribute }
          instance_variable_set "@#{attribute}".to_sym, value
          @attribute_keys ||= []
          @attribute_keys.push attribute
          self
        end
```

Thus, methods such as [`PersistenceSetup.setup`] that presently include the code

```ruby
        entity.instance_variable_set :@slug, attributes[:slug]
        entity.class_eval { attr_reader :slug }
```

would replace that with the single line `entity.add_attribute :slug, attributes[:slug]` and be done with that.

The [definition of the `#attributes` method](https://github.com/jdickey/new_poc/blob/d0ca00b/app/entities/user/core_attribute_setup/internals.rb#L25-L27) would then be replaced by the following:

```ruby
          entity.define_singleton_method :attributes do
            {}.tap do |ret|
              @attribute_keys.each do |key|
                ret[key] = instance_variable_get "@#{key}".to_sym
              end
            end
          end
```

Thoughts?

**Comment by mitpaladin** [comment]
Agreed, so this would serve to manage the `attributes` and the writer/reader for `properties` would further enforce the distinction

**Comment by jdickey** [comment]
*D'oh!*

When I change `UserPasswordEntityFactory.create` from

```ruby
  def self.create(attribs_in, password)
    entity = UserFactory.create attribs_in
    entity.class.class_eval do
      attr_accessor :password
      attr_accessor :password_confirmation
    end
    entity.password = password
    entity.password_confirmation = password
    entity
  end
```

to

```ruby
  def self.create(attribs_in, password)
    entity = UserFactory.create attribs_in
    entity.add_attribute :password, password
    entity.add_attribute :password_confirmation, password
    entity
  end
```

all but one of the `UserRepository` spec errors go away. (That spec fails because all the attributes in the result entity other than `created_at` are `nil`; i.e., it's a new entity).

**Comment by jdickey** [comment]
One of our longest-lasting, infrequent Heisenbugs is now repeatable using Commit fb5eae1. To repeat it, run the command line

```
bundle exec rspec spec/controllers --seed 45354
```

(You may wish to also include the command-line parameter `-f p` for shorter output.)

This will yield the error

```
 1) UsersController GET 'index' assigns the non-Guest users to the :users item
     Failure/Error: expect(index_user[attrib]).to eq user[attrib]
       
       expected: "jruser29@example.com"
            got: "jruser33@example.com"
       
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:65:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:64:in `each'
     # ./spec/controllers/users_controller_spec.rb:64:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/users_controller_spec.rb:62:in `each'
     # ./spec/controllers/users_controller_spec.rb:62:in `each_with_index'
     # ./spec/controllers/users_controller_spec.rb:62:in `block (3 levels) in <top (required)>'
```

Now to figure out *why*.

**Comment by jdickey** [comment]
A bit of investigation of the repeatably-failing spec shows that, as of Line [56](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L56) of `users_controller_spec.rb`, `users` (the array initialised in the [`before :each` block](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L41) for the spec) and `index_users` (which is loaded from the [`index` action](https://github.com/jdickey/new_poc/blob/fb5eae1/app/controllers/users_controller/action/index.rb#L16), getting its data from the [`UserRepository#all` method](https://github.com/jdickey/new_poc/blob/fb5eae1cb6ca8d62a54365e233e8893fa9550e48/app/repositories/user_repository.rb#L13)), have the same *data* but in a different *order*.

Setting a breakpoint at line 56 of `users_controller_spec.rb` allows us to see that the sequence of user names in `users`, which are each of the pattern "J Random User Number *n*", has values of *n* in the sequence *29, 30, 31, 32, 33*; the sequence in `index_users` at that point is *33, 29, 30, 31, 32*. At first I thought that perhaps the filtering done in [`UserRepository#all`](https://github.com/jdickey/new_poc/blob/fb5eae1/app/repositories/user_repository.rb#L13) might have skewed the ordering. However, adding a breakpoint there and accessing the database directly (via `UserDao.all` yielded the second sequence. This strongly suggests that the fault somehow lies at [the point](https://github.com/jdickey/new_poc/blob/fb5eae1/spec/controllers/users_controller_spec.rb#L40-L41) where we first instruct the DAO to add a record matching an entity to storage and then add that entity to an internal list. It seems likely that *this* is caused by some internal caching within the database driver and/or an interaction amongst the various moving parts used for data persistence in the test environment.

So what to do? Our `UserRepository#all` method is already [filtering out](https://github.com/jdickey/new_poc/blob/fb5eae1/app/repositories/user_repository.rb#L13) the Guest User from the returned results; perhaps the most expedient fix is to change that method so that it also sorts the results by slug?

Should that ordering be at the repository level or at the index-action level? After thinking about it, I'd argue for the action level; at present, this is the only User action that cares about ordering of multiple records.

**Comment by jdickey** [comment]
Progress. We're down to 69 failures in 36 feature specs (every single spec in the feature specs, in other words). The good news is that they're all the exact same "undefined method `parameterize' for nil:NilClass" at line [94](https://github.com/jdickey/new_poc/blob/dd67750/app/helpers/application_helper/build_menu_for.rb#L94) of `app/helpers/application_helper/build_menu_for.rb`, which is getting the offending `mil` value when it's trying to get the name of the current user. Fix that, and it's reasonable to expect that we'll be back on track and ready to merge this PR back into `master` (and have smoother sailing converting Post entities).

**Comment by jdickey** [comment]
As expected, a one-line change dramatically reduced, but did not yet eliminate, breakage. The expected result is that no single change is obviously going to eliminate all remaining problems. We see patterns, however.

**Comment by jdickey** [comment]
Down to 17 failures. Getting closer.

**Comment by jdickey** [comment]
Two failures left, from [a single feature spec](https://github.com/jdickey/new_poc/blob/24e3d28/spec/features/user_can_log_in_and_out_spec.rb). Both error dumps are identical:

```
     Failure/Error: click_on 'Update Profile'
     ActionView::Template::Error:
       No route matches {:action=>"show", :controller=>"users", :id=>nil} missing required keys: [:id]
     # ./app/views/users/edit.slim:2:in `_app_views_users_edit_slim__3079230695813737489_70350753904780'
     # ./app/controllers/users_controller.rb:97:in `on_update_failure'
     # ./lib/action_support/broadcaster.rb:11:in `broadcast_failure'
     # ./app/controllers/users_controller/action/update.rb:32:in `rescue in execute'
     # ./app/controllers/users_controller/action/update.rb:28:in `execute'
     # ./app/controllers/application_controller.rb:60:in `block in def_action'
     # ./spec/features/user_cannot_be_updated_invalid_data_spec.rb:17:in `block (3 levels) in <top (required)>'
```

**Comment by jdickey** [comment]
Right. The remaining issue (the link in the previous comment has been [fixed](https://github.com/jdickey/new_poc/blob/24e3d28/spec/features/user_cannot_be_updated_invalid_data_spec.rb)) hinges on our change whereby entered `password` and `password_confirmation` values are no longer returned from a call to an entity's [`#attributes`](https://github.com/jdickey/new_poc/blob/24e3d28/app/entities/user/core_attribute_setup/internals.rb#L40-L44) method. This has implications for [`Entity::Action::Update::Internals::BadDataEntity`](https://github.com/jdickey/new_poc/blob/24e3d28/app/controllers/users_controller/action/update/internals/bad_data_entity.rb), which recreates the [wrong entity class](https://github.com/jdickey/new_poc/blob/24e3d28/app/controllers/users_controller/action/update/internals/bad_data_entity.rb#L32) if the errors being investigated have to do with passwords. Oops.

**Comment by jdickey** [comment]
Light seems to dawn.

1. We're creating the wrong type of entity in [`BadDataEntity#initialize`](https://github.com/jdickey/new_poc/blob/c6feaff/app/controllers/users_controller/action/update/internals/bad_data_entity.rb#L11); we should be checking whether `data` has any password/confirmation values and, if so, use the `UserPasswordEntityFactory` to create the entity, rather than the `UserEntityFactory` (which isn't being used either);
1. Even if we do that, `UserPasswordEntityFactory` doesn't add validations for the `password`/`password_confirmation` attribute pair, so there's no way a mismatch would ever be considered invalid.

"Close only counts in horseshoes and hand grenades."

**Comment by jdickey** [comment]
Here's a ponder: Run

```
bundle exec rspec spec/entity_factories/user_password_entity_factory_spec.rb -t focus
```

and look at the debugging output. Then read the factory [`.create`](https://github.com/jdickey/new_poc/blob/d57245c/app/entity_factories/user_password_entity_factory.rb#L38-L47) method, with particular attention to the [`Internals.add_validations`](https://github.com/jdickey/new_poc/blob/d57245c/app/entity_factories/user_password_entity_factory.rb#L28-L33) method. If either of you can shed light on why [this spec](https://github.com/jdickey/new_poc/blob/d57245c/spec/entity_factories/user_password_entity_factory_spec.rb#L78-L85) fails, you're doing better than I at 0230 on a Thursday morning. :unamused:

**Comment by jdickey** [comment]
...and the conclusion reached after some rack time is that I *don't care* why the ActiveModel validations aren't working; I'll implement my own analogues again, declare victory and get out to do the next thing.

**Comment by jdickey** [comment]
The [two](https://github.com/jdickey/new_poc/commit/49fadba#commitcomment-10282638) [notes](https://github.com/jdickey/new_poc/commit/49fadba#commitcomment-10282672) in the preceding commit may denote something to stick a new dev on as part of onboarding, but I'll take what I can get for now.

**Pull request merged**
