### PR TITLE
Clawing back Post entities.

### PR DESCRIPTION
**Pull request by jdickey**
Per Issues #54 and #240. Not as "unbuilt Rails dependencies", but the door is very much open for Gemification later should the need/desire arise.

### CODE REVIEW

**Comment by jdickey** [comment]
Oh, hello again, Issue #250; we hardly knew you were gone. You're back! :unamused:

**Comment by jdickey** [comment]
`#build_body` and `#build_byline` (and arguably `#post_status`) **do not belong** in a "core domain entity". They are *explicitly* presentational details. They originated in helpers and decorators when this was a more traditional Rails-Way app; got lumped into the `User` entity as temporary expedients, and have long since outlived their welcome. They should remain part of the `User` entity for *only as long as needed* to prove interoperation with the existing pseudo-Gem API and then relocated (with calling code updated as well, obviously).

**Comment by jdickey** [comment]
Quoting the most recent post commit:

> Note that this iteration of `BylineBuilder' (and `TimestampBuilder`) wrap some knowledge of "what's inside a `Post` entity" that they really shouldn't. The (coming) rework to rip presentation-like helpers out of the `Post` entity should take an ISP approach to this with a `Post::Status` class or some such.

**Comment by jdickey** [comment]
Now to clean the mother up, starting with getting presentation details out of the "core entity". This can be done in several ways:

#### Directly Nested Classes

Create nested classes, e.g., `Entity::Post::StateInformation`, with methods `#persisted?`, `#published?`, `#draft?`, etc. Code wishing to use such would create a separate object. As this is a different *logical* architectural level than existing nested classes (which are private internals), some rejiggering of *those* might be required

#### Accessor Handing Back a Class Instance

This is a variation on the above scenario where, instead of directly instantiating an `Entity::Post::StateInformation` class, you'd call a `#stateInformation` method on the `Post` you were interested in, and that would hand you back a state-information instance populated with the requesting `Post` instance. Not sure how I like this; it is a Demeter-compliant rework of the above but still pollutes the "domain entity" class API with non-core methods.

#### Separate Concept; Separate Factory Type

To get the state information for a `Post`, you'd have code like

```ruby
  info = Entity::PresentationFactory::StateInformation.build post
  # ...call `info.draft?` or whatever you like...
```

Can we all agree, "ick! ptui!"?

#### Dynamic Moldule Mixin

Here, we don't have a dichotomy between a `Post` and something with information *about* a `Post`; we add the code that knows about the details we want *to* a `Post`.

```ruby
  post.extend Entity::PostExtensions::State
  do_something_awesome if post.published?
  # ...
```

Does this violate SRP? Absolutely. Does this incur more technical debt/code bloat/general ugliness than any of the above alternatives? I'm going to grab a few hours sleep and think about that one.

**Comment by jdickey** [comment]
And the winner from the four options listed is…Option Number Five, factory class methods.

With an implementation similar to

```ruby
module Entity
  class Post
    # ...
    def self.withStateExtensions(attributes)
      Post.new(attributes).extend Entity::Post::Extensions::State
    end
    # ...
```

This gives us the "dynamic module mixin" setup without the *calling code* having to know anything about the internal arrangement of the extension classes, or even that there *is* an extension class.

**Comment by jdickey** [comment]
And...after playing with [that implementation](#issuecomment-85332323) for a day, I'm going back to a Demeter-compliant variant on "Dynamic Module Mixin"

```ruby
module Entity
  class Post
    # ...
    def withStateExtensions
      extend Entity::Post::Extensions::State
    end
    # ...
```

This lets client code extend an existing instance without having to know exactly what it's extending *with*.

**Comment by jdickey** [comment]
Right; so what have the last ~5 commits accomplished?

1. We've broken out the most obviously explicitly presentation-related methods, including a pseudo-attribute (`#post_status`) of the `Post` entity into a module that *is not* mixed in by default. In a live app, it would be mixed in only as part of generating views;
1. We've made relationships within that module's supporting code, that is used *only* by the methods in that module, blindingly explicit.

Compare this with the approach used for modularising the `User` entity earlier; even though that class now has conceptually clean implementation that should be easy for new developers to pick up and work on, all modules are loaded as part of the "meta-entity" `Entity::User`.

Here, by contrast, `Extensions::Presentation` is not part of the "main" `Entity:::Post` class, and must be loaded separately (through a Demeter-compliant method on the `Post` instance being extended).

#### Continuing On

What other extensions will/might we want to extract here?

1. Validation, with at least the current methods `#valid?`, `#body_or_image_post?`, `#registered_author?`, `#valid_author_name?`, and `#valid_title?`. One rationale would be that, in addition to any SOLID-based principled argument, that the rules for validation might well change in different contexts, and extracting such a module would be the least painful way to facilitate that;
1. Persistence, with `#slug`, `#created_at`, `#updated_at`, and `#persisted`. The justification here would be analogous to that for validation (above). Again, from the perspective of a value object such as an Entity, any knowledge of the persistence state of an individual entity is almost certainly presentation-related (which would tend to piggyback it onto the just-completed `Presentation` extension).

#### Ponderables

1. Even though entity *code* has been separated from depending on an ORM (such as ActiveRecord), the *specs* currently load the entirety of Rails and RSpec for *each  and every example* individually. This slows unit-test execution by at least one order of magnitude, as pointed out by numerous writers;
1. We've invested man-months in building out "clean(er) architecture in Rails 4", along the way developing a nearly [Greenspun](http://en.wikipedia.org/wiki/Greenspun%27s_tenth_rule)-compliant implementation of DCI, which is one of the two in-production approaches to mitigating Rails and avoiding being [Slashdotted](https://en.wikipedia.org/wiki/Slashdot_effect). The other approach is demonstrated in [this talk](https://youtu.be/naTRzjHaIhE) by [Akira Matsuda](https://github.com/amatsuda), which can basically be summarised as "iteratively identify the bottlenecks in the Rails Way stack; sic your team on developing patches or replacement tools that ease your pain; iterate, iterate, iterate". Which is fine if you've a couple of hundred developers and an existing app with *thousands* of models; you've painted yourself into a very small corner that I'd really rather not join you in. Alternatives exist; we should have some intelligent rationale for evaluating them to avoid being sucked into the fad-of-the-week.

References:

1. [*Skinny Models — the DAO pattern for Ruby persistence](https://jdanger.com/skinny-models-the-dao-pattern-for-ruby-persistence.html), a blog post by Jack Danger Canty dated 20 July 2013;
1. *Trailblazer: A new architecture for Rails*, by Nick Sutterer. [Early-access book website](https://leanpub.com/trailblazer), [Github repo](https://github.com/apotonick/trailblazer).
1. *Fast Rails Tests* by Corey Haines. [Presentation slides](https://vimeo.com/30893836), [Golden Gate Ruby Conference 2011 presentation](https://youtu.be/bNn6M2vqxHE), [original blog post](http://articles.coreyhaines.com/posts/active-record-spec-helper/).
1. [Lotus](https://github.com/lotus/lotus) — another promising future tool for Rails Web development.

**Comment by jdickey** [comment]
Besides the above, what needs doing before we close out this issue? *Consistency.*

The `Post` and `User` entities at present display two radically different approaches to composition, SRP/ISP compliance and so on; what I've been collecting under the catchphrase *modularity*. We should pick a winning architecture from the two; thrash the other into compliance, and DRY up any shared code.

There's plenty left to be done before closing out #240 and #52, contrary to earlier expectations, but that should do it for *this* issue.

**Comment by jdickey** [comment]
Right; here's a "fun" little wrinkle:

`Entity::Post#initialize` sets up each instance variable in turn, based on the `attributes` `Hash` passed in. These could have originated in a form, a DAO, just about anyplace. None of those attribute sources know (or should know) about the intricacies of our modular composition. How to arrange things properly?

As I see it, we have two options:

1. Leave things as they are, with *all* attributes (not simply core attributes applicable in all situations) in the core entity class, as at present. Extensions such as `Persistence` use such attributes, but are not responsible for them. This defeats SRP by requiring that any change (say, adding a new `number_of_updates` attribute to `Persistence`) would require *two* things to change;
1. Have the `Post#initialize` method *ask* each `Extensions` module whether it knows about an attribute which is unknown to the core entity. This would be by way of a new, module-level method implemented by each extension which adds attributes. Tentatively called `uses_attribute?`, an implementation for the `Persistence` module as described under [`Continuing On`](#issuecomment-86435309) above, might read

```ruby
        def self.uses_attribute?(attribute)
          [:created_at, :slug, :updated_at].include? attribute
        end
```

Should a module's `#uses_attribute?` method return `true` for a given attribute, the core entity would extend itself with that module and retry the assignment.

Thoughts?

**Comment by jdickey** [comment]
Using the `uses_attribute?` method strategy in the preceding comment should eliminate the need for the `Entity::Post#extend_with_*` methods *assuming the attribute requiring an extension is specified to the initialiser*. This argues for replacing the current `instance_variable_set` hacks with proper attribute-writer methods that perform the same checks being proposed for the `#initialize` method. Or, better still, the "writers" simply bite the bullet and return a new instance with the attribute in question; that kicks things back to the initialiser.

**Comment by jdickey** [comment]
> ...the "writers" simply bite the bullet and return a new instance with the attribute in question; that kicks things back to the initialiser.

Sounds like a use case for one of the [two](https://github.com/hdgarrood/value_object) [Gems](http://disu.se/software/value-1.0/) mentioned in the [earlier comment](#issuecomment-86576903) as being for just such a use.

In the morning.

**Comment by jdickey** [comment]
Build delayed (and showed as failed) because Github connectivity from CodeShip was down for an hour just now. Seems to be resolved; 73fa17a is going as I type this.

**Comment by jdickey** [comment]
With the new "extensible attributes value object", we *still* need the `.uses_attribute?` class method I described in [this earlier comment](#issuecomment-86628728). Here's the basic flow as I now see it for setting the attributes in a new instance (from the point of view of `Entity::Post#initialize`):

1. Assign `@attributes[:core]` as [at present](https://github.com/jdickey/new_poc/blob/f9a5d21/app/entities/post.rb#L36). Note that one feature of `ValueObject::Base` is that it will ignore any initialisation-hash key/value pairs which do not have matching `has_fields` declarations;
1. Collect the attributes passed in to `#initialize` which were *not* assigned to `@attributes[:core]`. For the purposes of the following pseudocode, let's call that collection `other_attributes`;
1. Iterate through the `other_attributes`. For each `target_attribute`, iterate through the constants (naming extension modules) in `Entity::Post::Extensions`. For each `candidate` extension module, call its `.uses_attribute?` module method, passing in the current `target_attribute`;
1. If a particular `target_attribute` is matched by a particular `candidate` extension module, extend `self` with that `candidate` module. (This will add an entry to `@attributes` which can be accessed as `@attributes[candidate]`. Then have a line such as `@attributes[candidate] = @attributes[candidate].copy_with(attributes)`. This will send *all attributes* passed to `#initialize`; the attribute object will keep only the attributes for that module. Remove those "kept" attributes from `other_attributes` and iterate again;
1. If a particular `target_attribute` is *not* matched by the current `candidate` extension module, iterate to the next candidate until a matching module is found or all modules have been tried unsuccessfully (at which point the `current_attribute` is ignored);
1. Remove the `.uses_attribute?` method from `self`, as it is no longer needed (but was added by the last extension module merged).

Alternatively, rather than asking each module if it supports an individual attribute, we could build up a hash mapping extensions to the attributes they support (using a new `self.supported_attributes` method rather than the existing `self.uses_attribute?`. Then look to match attribute keys, and extend `self` with the matching modules.

Thoughts?

**Comment by jdickey** [comment]
That second idea dashed off in the last paragraph of the preceding comment *does*, on reflection, seem the better choice.

The `Post#initialize` method will instantiate a new `AttributeMapper` class. That class iterates its `Extensions` modules, building a hash using the module-name constant as  the key, and the return value from a (new) `.supported_attributes` module method (if it exists) as the values. (Those values will be identical to the return value of the module's attribute class' `.fields` class method.) The mapper will then transform the fully-built hash to one mapping attribute-name symbols to their supporting module (e.g., `:slug => Extensions::Persistence`). The `AttributeMapper` class will expose a method, `#module_for(key)`, which will return the value (module constant) for the specified `key` (attribute).

Once that mapping is built, the `Post` instance's `#respond_to?` method can use that to ask whether a method (attribute reader) is supported. `Post#method_missing` can then use the mapping to identify which module should be used to extend `self`, define a reader method for the given attribute dynamically (preventing later calls to that attribute reader from ever reaching `#method_missing`), and return that reader method's return value (the attribute in question).

That takes care of *reading* an attribute value, but how do we actually *set* it (in `#initialize`)? By adapting the earlier workflow. Now that `#initialize` has the mapper built up, we iterate the passed-in attributes building a list of the modules needed to support the specified attributes, load them, and "assigning to" that attribute (which creates a new version of the containing value object via a `private` attribute-writer method).

The end result will be that client classes (specs, Actions, etc) will be able to read attribute values without knowing, caring or being able to determine where and how those attributes are implemented. We get clean, SOLID implementation that should be easy to understand, maintain and adapt going forward.

**Comment by jdickey** [comment]
Bits to notice in the preceding two commits:

1. [`Entity::Post::AttributeExtensionMapper`](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post/attribute_extension_mapper.rb). Builds up a list of attributes implemented in each extension (and, called with a block, the entity core), then produces a `Hash` mapping each supported attribute to the module which implements it. This is used by
1. [`Entity::Post#method_missing`](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post.rb#L45-L58). If the requested method is an attribute reader for an attribute [determined to be supported](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post.rb#L34-L36), build a method on `self` that returns the named attribute and return the result of calling it. This guarantees that `#method_missing` will not be called again for that attribute for the lifetime of this object instance.
1. [`Entity::Post::Extensions::Persistence.supported_attributes`](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post/extensions/persistence.rb#L26-L28) is the new, *new* way for an extension to report the attributes it defines to  [`Entity::Post::AttributeExtensionMapper`](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post/attribute_extension_mapper.rb) (and hence to `Entity::Post`). A Ruby purist might well choose to simply `delegate` this method to `PersistenceAttributes.fields`; I feel this is more intuitively explicit to readers less experience with delegation. And, finally,
1. [`Entities::Post#attributes`](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post.rb#L64-L69) (and its `private` [supporting](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post.rb#L83-L89) [methods](https://github.com/jdickey/new_poc/blob/8254f01/app/entities/post.rb#L77-L81)) hands back a value object with all attributes known to this instance of the entity. In a break from previous implementations, attributes with `nil` values *are not* stripped from the value object (as they had been when this was simply a [`FancyOpenStruct`](https://github.com/tomchapin/fancy-open-struct).

**Comment by jdickey** [comment]
Well, pffffft. When we had the "doubled" entity classes (`Entity::Post` and `Newpoc::Entity::Post`), `PostFactory#create` would hand back an instance of the latter that would Just Work with code expecting the former. Too bad that doesn't quite work the other way around. One instance where that bites us is in `PostRepository#add`, which takes an entity as its parameter. The old `Newpoc` entity kept its attributes in a (mutable) `Hash`. The new version uses a [`ValueObject`](https://github.com/hdgarrood/value_object) which supports conversion to `Hash` *via an explicit call to its `#to_hash` method*. The call is not needed if a `ValueObject` is being passed *to* something expecting a `Hash`, but calling `Hash` methods *directly on the `ValueObject`* is obviously a boo-boo. See [`repository_base` issue 19](https://github.com/jdickey/repository-base/issues/19).

**Comment by jdickey** [comment]
Now that [`repository_base` issue 19](https://github.com/jdickey/repository-base/issues/19) is closed and the Gem is [updated](https://github.com/jdickey/repository-base/releases) (to version 0.3.1), we should be able to get a *bit* farther tonight.

**Comment by jdickey** [comment]
And with Commit d6b0d37 (which was a plug-and-play on top of 7b43fbe), we're down to *three* non-feature spec files with failing examples:

1. `spec/repositories/post_repository_spec.rb`;
1. `spec/controllers/posts_controller/action/create_spec.rb`; and
1. `spec/controllers/posts_controller_spec.rb`.

That's (fairly obviously) the order I'll hit them in in a few hours. :sleepy:

**Comment by jdickey** [comment]
What breaks the specs for `PostsController::Action::Create` is that we actually have two different use cases for `PostFactory.create`. It can be called with

1. A DAO record (as suggested by the method's parameter name), or something that quacks enough like one (returning a `Hash`-like object from `#attributes`); *or*
1. An actual `Hash`, as from [`ActionSupport::RepositoryAdder#add`](https://github.com/jdickey/new_poc/blob/9b4dfd2/lib/action_support/repository_adder.rb#L18).

That latter *may* be the only case of call;ing `.create` with a `Hash`; its code does not lend itself well to constructing a value object before making the call; and it seems reasonable to expect that passing in a `Hash` of attributes *should* Just Work and hand you back an entity custom-made to your specifications.

So why does changing `PostFactory` (and presumably, eventually, `UserFactory`) to accept a `Hash` as well as a "record" scream at me, "You're missing something"?

**Comment by jdickey** [comment]
When you're *really* tired, it's *far too easy* to let refactorings you have in the back of your mind as "ought to get around to this" to find their way, haphazardly, into what you're working on — only to be discovered a day or three (or more) later.

The latest example is [this snippet](https://github.com/jdickey/new_poc/blob/9b4dfd2/spec/controllers/posts_controller/action/create_spec.rb#L158-L173) from the spec for `PostsController::Action::Create`, verifying that draft/published status is correctly reported:

```ruby
      context 'public' do
        let(:post_data) do
          {
            author_name: current_user.name,
            title: 'A Title',
            body: 'A Body',
            post_status: 'public'
          }
        end

        it_behaves_like 'a successful post that'

        it 'is not a draft post' do
          expect(actual).not_to be_draft
        end
      end # context 'public'
```

What had me going around in circles *all day long* is that the "is not a draft post" spec was failing (reporting `actual.draft?` as `true` rather than the expected `false`) even though I knew and could prove the data initialising the post (`post_data`, above) had not changed. We'd "just" reworked how non-core bits of the `Post` entity (like publication status) got mixed into a live entity instance. Or was that all?

Turns out that the old code looked for the value of the `post_status` field, as above, to tell it if it was a draft or published post. The code I'm working on now (which I'll push here shortly) said "hang on a minute; it's a `draft` if there's no `pubdate` field value, and `published` if there is".

Which is right actually depends on *where the data was originated from*; if an entity represents data that was entered in a form, then having the string field state be the toggle was handy, as it was easy to map that to the form logic (you basically didn't need any). If the entity represents something that had been constructed based on a persisted item, however, then the publication date becomes a logical choice: no `pubdate`, it hasn't been published, and therefore it's a draft.

This leads to two possibilities for resolution:

1. *`pubdate` wins*. The `post_status` attribute is a computed value dependent on `pubdate`. This implies that the logic for setting up and responding to form-entry data would be responsible for the conceptual translation;
1. *`post_status` wins*, and becomes a real attribute (as opposed to a computed one)  on the `Post` entity. The `pubdate` attribute remains as a vestigial `nil` value in a draft post.

"Hang on", I can hear you thinking, "why not just say that *both* have to be maintained, and it's only a 'published' post when *both* are set appropriately?" Might I take that as you volunteering to find the (almost inevitable over time) bugs from the two attributes getting out of sync? A Single Source of Truth™ is a Very Good, even a *necessary*, Thing.

**Comment by mitpaladin** [comment]
ok, I would opt for a real attribute for `post_status`.  There's no reason why something with a `pubdate` might not then be set to some other state besides Published, so best be explicit.

**Comment by jdickey** [comment]
At this point, I'm inclined to give the nod to `pubdate`, which is a breaking change from what exists on the current `master` branch. The argument is that `pubdate` is an authoritative answer to the question, "has this `Post` been published", whereas `post_status` is not simply language-specific, but enforces an assumption about the user interface and API of the code using the entity.

**Comment by jdickey** [comment]
Having a full attribute for `post_status` is redundant until/unless we get to a point where we support marking published posts as private again, or where we support other publication states (private/by invitation only, otherwise restricted, etc), or maintain an audit trail for a given post (created on 2 April, published on 6 May, marked as public again on 11 October...). Any of those would require a fundamental rethink to post status persistence and management that would render either currently-proposed alternative obsolete and require significant changes to the relevant logic in the `Post` entity (another argument for isolating it in an extension as now). However, *none* of these *potential future* changes are presently in scope; what's needed is the simplest solution that meets current needs yet leaves the door open to future enhancement with minimal unnecessary pain. Leaving the `Publication` extension [as it presently stands](https://github.com/jdickey/new_poc/blob/9b4dfd2/app/entities/post/extensions/publication.rb) appears to accomplish this.

**Comment by jdickey** [comment]
> Yet another reminder that *any* Rails component is massively intertwined with anything else it touches, even something as seemingly benign and easily encapsulated as error tracking. We've been here before.

Indeed we have been here before; the problem is how to support (and expose) the `ActiveModel::Validations#errors` method. The unbuilt-Gem version of this code simply [included](https://github.com/jdickey/new_poc/blob/c34639e/lib/newpoc-entity-post/lib/newpoc/entity/post.rb#L21-L22) most of ActiveModel (by way of [Chris Griego's](https://github.com/cgriego/) [ActiveAttr](https://github.com/cgriego/active_attr) repackaging) and used [ActiveModel validations](https://github.com/jdickey/new_poc/blob/c34639e0831413da7ca90d2f7261ecff862477ca/lib/newpoc-entity-post/lib/newpoc/entity/post.rb#L26-L29) directly. I'd actually prefer the *now-existing* validation logic to the ActiveModel validations and just piggyback on `ActiveModel::Errors` (as shown in the commented-out code in the last commit's [`Entity::Post::Extensions::Validation` code](https://github.com/jdickey/new_poc/blob/48a3722/app/entities/post/extensions/validation.rb); It Would Be Very Nice If™ we were to stumble across a similarly-improved encapsulation/repackaging of `ActiveModel::Errors`; I was never clear on why the `ActiveModel::Errors` class needed access to the model instance itself since, by calling that class' `#add` method, one specifies the field name to be charged with the error.

**Comment by jdickey** [comment]
I found [this](http://www.railshelp.com/ActiveModel::Errors), which tells me basically what I remember from the Rails 3.2 days (but adds new methods that must be supplied/overridden). A quick `bundle exec rails c` session and copy-and-paste, and we have a strategy again. :unamused:

**Comment by jdickey** [comment]
Hard to find goofs like that last (Commit 3d0e874) with a build that's catastrophically broken overall… but we've made *significant* progress in that area tonight. Finally.

**Comment by jdickey** [comment]
24 of 67 examples in [the spec for `PostsController`](https://github.com/jdickey/new_poc/blob/3d0e874/spec/controllers/posts_controller_spec.rb) have been broken by the changes in the `Post` entity and its ecosystem; at least half of them are bitching that `Newpoc::Entity::Post` doesn't exist anymore. Fine; we can deal with that. Once *that* has a green bar, we turn our attention to the 19 of 37 feature specs currently broken; that *should* be almost clerical-level fixes (and arguably points to the brittle over-specificity of those specs).

The light up ahead is *highly* unlikely to be the 4.15 from Dubuque.

**Comment by jdickey** [comment]
Now all that stands between us and a green bar worthy of merging is 18 busted feature specs, and Issue #253.

**Comment by jdickey** [comment]
...and the reason those 18 feature specs are "busted" is because we're trying to use a `Post` entity with Rails forms that expect attributes to work the same way as they do in `ActiveModel`, and we've just spent *40 commits and 16 days*(!) breaking that assumption.

In plain, SOLID-hostile Rails, attributes on a module are individually and collectively readable and writeable. Looking at it from Rails' perspective, that's sensible. There is no concept of an "entity" or "value object" in Rails, and a model is *defined as* something that defines an object interface to a database table or relation. If your logic doesn't fit into a model, controller or (*shudder*) view in Rails, Rails' perspective is that it doesn't belong in the app, full stop. This is a huge part of the reason why there are so many "alternative stacks" out there now (that mostly didn't exist in useable form in 2012) that try, with varying degrees of success, to build a sane architecture on top of, around, and/or in spite of Rails; this is why the era of dominance of the [omakase Rails architecture](http://david.heinemeierhansson.com/2012/rails-is-omakase.html) is called the ["lost years"](https://duckduckgo.com/?q=rails+architecture+lost+years); and so on. The upshot is that forms can do whatever they want to models, which have limited detection/notification capabilities and no protection beyond validation.

With our [current `User` entity](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/user.rb), [`attributes`](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/user/core_attribute_setup.rb) are [set up](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/user/core_attribute_setup/internals.rb) so that the `#attributes` method is merely a collection of individual attribute values, which are each readable and modifiable identically to Rails, so that the following would work:

```ruby
  # `user` comes in from Somewhere Else
  user_attributes = user.attributes
  user.attributes = user_attributes.merge profile: 'Profile', email: 'foo@example.com'
  user.email # => 'foo@example.com'
  user.profile = 'Other profile data'
  user.attributes[:profile] # => 'Other profile data'
  # ...
```

Changing an attribute to an invalid value is not detectable until (and unless) the `#valid?` method is called on the entity containing the now-invalid attribute. This has been proven over the years to be a reliably consistent source of bugs.

Our [current `Post` entity](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/post.rb) mitigates that through a surprisingly elaborate mechanism whereby the `#attributes` method returns a *value object* containing the results of merging a [core-attributes value object](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/post.rb#L18-L20) and the attribute value objects of any "entity extensions" which define them (such as for [`Persistence`](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/post/extensions/persistence.rb#L24-L26)). When individual attribute readers are called, those are intercepted by [`Post#method_missing`](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/post.rb#L61-L74), which dynamically defines a new reader method for that attribute and calls it. The reader method looks up the specified attribute in the internal "attribute set" object used to build `#attributes`. Hence, `#attributes` is changed from the convenience method as in `User` to a value object encapsulating read-only access to a given set of attribute values. (To retrieve the attributes for a `Post` instance as a `Hash`, you would call `post.attributes.to_hash`.)

It should be pretty obvious by now how Rails is mortally confused by the Newest Order of Things. Back in ancient times (relative to this project) when we defined the concepts of entities, DAOs, repositories, and so on, anything that was entirely Rails presentation- or persistence-oriented, such as forms, was declared to be reliant on implementation objects (DAOs) rather than domain entities. The `User` entity honoured that convention in the breach by having its attributes quack like ActiveModel's well enough that the forms at least *think* they can work with them. `Post` breaks that by breaking the Rails conventions for `attributes`.

This leaves us with (at least) three options:

1. We could change the concept of attributes inside an entity from "*attributes within an entity* are immutable" to "*the current state of the set of attributes in an entity* is immutable; setting an attribute causes the entire value object containing the attributes to be replaced";
1. Reintroduce the entity/DAO layer, so that Rails forms (etc) only deal with ActiveModel-compliant (now ActiveRecord::Base) objects (DAOs);
1. Rewrite `Post` with an entity class explicitly patterned after the current `User`. This includes loading all "extension" mixins on each newly-created `Post` (currently, validation and persistence are only mixed in on explicit request). Critically, it also would reverse the currently-implemented semantics of `Post` attributes, requiring each attribute to be a separate instance variable.

In hindsight, the on-request loading of persistence and validation on the `Post` entity should have been red flags that what we were really asking for was a DAO. This realisation, in my current view, makes the second option (reintroducing the entity/DAO boundary) even moire compelling; code that makes such requests is almost certainly really asking for a DAO rather than an entity.

Whatever we wind up doing, we're going to have to go back and ensure that the `User` implementation works like the revised/replaced `Post` and factor out common code between the two.

Yep, it's Monday. :unamused:

**Comment by jdickey** [comment]
The above isn't *entirely* accurate. Validation is a domain-level concept *as well as* an implementation-level concept (domain rules often go beyond simple single-table data-consistency issues). It *should not* be an "extra", on-request feature of an entity, but should be an essential feature of any entity.

How does that jibe with `Post`'s initialisation-parameter-driven, modular approach to "extensions"? It argues forcefully that ActiveModel's (or other similar) internal DSL is *brilliant* in this context; anything that can call `class_eval` on an entity instance (like mixed-in modules) can add new validation rules to the object.

But it does restate what the current `User` entity implies: that validation of core attributes is a basic feature that should be part of the basic, no-options-added instantiation of an entity. `User` currently does this and `Post` makes it [blindingly obvious](https://github.com/jdickey/new_poc/blob/06ac189/app/entities/post/extensions/validation.rb#L44-L46) what core-attribute validation is (without using the DSL); all that is required is a great lot of refactoring.

**Comment by jdickey** [comment]
Closing after the merge of PR #254, which replaced this.

**Pull request closed without merging**
