### PR TITLE
Retooling with Contracts, Attire and possibly a couple of other such bits. Round One.

### PR DESCRIPTION
**Pull request by jdickey**
As described in Issue #263.

### Contracts and Attire

We're going through and adding [Contracts](https://egonschiele.github.io/contracts.ruby/) just about everywhere. It decouples method parameter/return validation from the method code; if a contract is violated, an error will be raised that the caller can rescue and learn (almost) all about what went so Horribly Wrong.

[Attire](https://github.com/mushishi78/attire) (see writeups [here](http://pigeons-and-creoles.co.uk/tools/attire-initialization-and-private-getters) and [here](http://pigeons-and-creoles.co.uk/tools/attire-dependency-injection/)) for reducing initialiser boilerplate is also useful, ,but (as far as I've been able to determine to date) can't be used simultaneously with Contracts on the same method.

#### First Alternative, using Attire

For example, if you originally had code that looked like

```ruby
class Widget
  def #initialize(foo, bar = nil, baz = 42)
    fail ':foo is too long!' unless foo.is_a?(String) && foo.length < 3
    @foo = foo
    @bar = bar
    valid_baz = baz.is_a?(Fixnum) && baz % 2 == 0
      && baz >= 40 && baz < 50
    fail 'Bad :baz!', unless valid_baz
    @baz = baz
  end
  # ...
  private

  attr_reader :foo, :bar, :baz
end
```

then you could replace that whole method with

```ruby
class Widget
  attr_init :foo, bar: nil, baz: 42
  # other methods as before; nothing required in `private` by the above
end
```

#### Second Alternative, Using Contracts (and `#initialize`)

If you want to use Contracts, the *easiest*, *cleanest* thing to do is to not use `attr_init` to replace `#initialize`, but have a (dramatically) simplified version of thte original:

```ruby
class Widget
  include Contracts
  include Contracts::Invariants

  invariant(:foo) { foo.length < 3 }
  invariant(:baz) { baz % 2 == 0 && baz >= 40 && baz < 50 }

  Contract String, Maybe[Symbol], Num => Widget
  def #initialize(foo, bar: nil, baz = 42)
    @foo = foo
    @bar = bar
    @baz = baz
    self
  end
  # other methods as before
  private

  attr_reader :foo, :bar, :baz
end
```

In this example, `#initialize` *only* does initialisation; validation of incoming parameters (and returned value) has been extracted into the `Contract` and `invariant`s above it.

### Discussion

Which is more important in each case is a judgment call; if you trust other code to deal with sloppy initialisation parameters (possibly because the attributes that those parameters initialise are being passed to methods that have Contracts on them), then Attire will get rid of "obvious" boilerplate for you.

You can have Contracts on *any* instance method of a class that includes the module, the [tutorial](https://github.com/egonSchiele/contracts.ruby/blob/master/TUTORIAL.md) goes into all the glorious detail. You can specify contracts that validate parameters/return values using any of roughly twenty built-in contracts and, if those don't quite do what you want, it's almost absurdly easy to [define your own](https://github.com/egonSchiele/contracts.ruby/blob/master/TUTORIAL.md#defining-your-own-contracts). Contracts are constants and (like everything else in Ruby) class instances; which means that you can establish your own app-wide or shop library and reuse as the need arises.

You could, of course, do something like

```ruby
class FooValidator
  def self.valid?(foo)
     foo.is_a?(String) && foo.length < 3
  end

  def self.validated_value!(foo)
    fail 'Foo is too long!' unless valid?(foo)
    foo
  end
end


class Widget
  attr_init :foo, bar: nil, baz: 42 do
    @foo = FooValidator.validated_value! foo
  end
```

but that gets clunky *fast*, IMO.

### But I "Really Want" *Both*, Blastit!

I started writing out another option, "inspired by"  [the DI blog post](http://pigeons-and-creoles.co.uk/tools/attire-dependency-injection/)'s example, and abandoned it when my *shortest* working example exceeded *three times* the length of the first Contracts example, above. *Either* you have a Contract on `#initialize`, and write it out as usual, *or* you use Attire's `attr_init` and inject validator *classes* as in the aforementioned DI example. The mildest criticism of the "let's use both" aborted example was that all the validation and initialisation were being done *at least* twice. No, thank you.

### Enlightened Inspiration, or Inspired Enlightenment

And then I thought of *this:*

```ruby
class Widget
  include Contracts
  include Contracts::Invariants

  attr_init :foo, :bar, :baz do
    validate_initialisers! foo, bar, baz
  end  
  
  invariant(:foo) { foo.length < 3 }
  invariant(:baz) { baz % 2 == 0 && baz >= 40 && baz < 50 }

  # other public methods; you'll want to do something besides `#initialize`!

  private

  Contract String, Maybe[Symbol], Num => Bool
  def validate_initialisers!(foo, bar, baz)
    true
  end

  # other private methods, as needed
end  
```

We've got our `attr_init` (with the caveat that it has to call *an instance method* in the block that really doesn't do anything except exercise its Contract). We've got *one* "extra" method (`#validate_initializers!`, which can and likely should be `private`). We've got everything in the same single class as we had at the beginning &mdash; no `WidgetFactory`; no `FooValidator`; no egregious boilerplate &mdash; and we've shortened the body of our `#initialize` method (or its equivalent) down to one line (plus the Contract on `#validate_initialisers!`, but that was the point of the exercise).

That's good enough for now, I think.

### CODE REVIEW

**Comment by jdickey** [comment]
Right; let's now go and update the classes we've changed in the previous two commits (63403ef and 4144fa6) as per "Enlightened Inspiration" in the (current version of the) initial comment.

Those files are:

1. [`app/decorations/posts/byline_builder.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/byline_builder.rb)
1. [`app/decorations/posts/html_body_builder.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/html_body_builder.rb)
1. [`app/decorations/posts/html_body_builder/image_post_builder.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/html_body_builder/image_post_builder.rb)
1. [`app/decorations/posts/html_body_builder/image_post_builder/element.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/html_body_builder/image_post_builder/element.rb)
1. [`app/decorations/posts/html_body_builder/image_post_builder/fig_caption.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/html_body_builder/image_post_builder/fig_caption.rb)
1. [`app/decorations/posts/html_body_builder/image_post_builder/figure.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/html_body_builder/image_post_builder/figure.rb)
1. [`app/decorations/posts/html_body_builder/image_post_builder/image.rb`](https://github.com/jdickey/new_poc/blob/4144fa6/app/decorations/posts/html_body_builder/image_post_builder/image.rb)

Specs *shouldn't* have to change.

*Reminder to self:* Easy to build that list with [this SO answer](http://stackoverflow.com/a/3144810/1372767) to get the list of files; turning it into a list of Markdown links is an editor search-and-replace presto-change-o left as an exercise for the reader.

**Comment by jdickey** [comment]
A reminder on keyword arguments with both `attr_init` and Contracts.

### `attr_init`

If you have code like

```ruby
class Foo
  include Contracts

  attr_init :foo, bar: nil do
    # ...
  end
  # ...
end
```

you *must* call `Foo#initialize` similarly to

```ruby
  quux = Foo.new foo: some_value, bar: some_other_value
```

i.e., the `foo:` and `bar:` "keyword parameters *must* be specified. They're not *really* keyword parameters; they're keys in a Hash that's assembled and sent as the (only) parameter to `Foo#initialize`.

### Contracts

Conversely, if you have a method such as

```ruby
class Bar
  include Contracts
  # ...

  Contract String, Maybe[Symbol] => Bool
  def panic(reason, severity)
    # do something urgent with `reason` and `severity`
    should_we_die?
  end
```

obviously, you *don't* use keyword arguments when calling that. If you wanted to, you'd declare you `Contract` *as though the only parameter was a Hash:*

```ruby
  Contract( { reason: String, severity: Maybe[Symbol] } ) => Bool
  def panic(reason:, severity:)
    # do something urgent with `reason` and `severity`
    should_we_die?
  end
```

because that's how `Contracts` *sees* keyword arguments — as entries in a Hash.

Yes, I'm only writing this down because I've beat myself against it *n* too many times, for some arbitrarily large value of *n*. :unamused:

**Comment by jdickey** [comment]
Hmmm. We have a problem; adding a do-nothing spec with a single example breaks RSpec, as written up in [this Gist](https://gist.github.com/jdickey/b78dde0d5ff917d4e5d3). I'll yell for help in all the usual places (later) in the morning; it's after 3 AM and my mind is deep-fried to a deep charcoal black.

**Comment by jdickey** [comment]
I've been flailing on an interesting and *intensely* frustrating problem trying to retrofit a spec for one of the `UsersHelper` support classes, as I've been recording in [this Gist](https://gist.github.com/jdickey/b78dde0d5ff917d4e5d3).

Any suggestions are more than welcome.

**Comment by jdickey** [comment]
Here's what I know so far in re the new-support-class spec snafu mentioned earlier:

1. Checked out `master` (currently at Commit f76896b);
1. Checked out a new branch, `explorer`, from that commit, and rebundled;
1. Applied [this patch](https://gist.github.com/jdickey/322d9b73e3c7213f9d3d) which changes the `Regexp` syntax in [`spec/decorations/posts/byline_builder/formatted_time_tag.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/decorations/posts/byline_builder/formatted_time_tag.rb); something changed in regex interpretation between 24 April and 4 May, and this patch fixes that;
1. Ran `bundle exec rake db:drop:all && bundle exec rake db:setup && bundle exec rake db:seed && bundle exec rake setup_test_db && tput bel' to reset the development and test databases; the terminal bell at the end gives you a confirmation that nothing was reported to have died (as opposed to simply not outputting an error message);
1. Ran `bundle exec rake` and got a green bar. This is *presumably bogus*, as we'll see;
1. Built a list of all spec files by running `all_specs=`find spec -name \*_spec.rb` in the terminal;
1. Ran `for i in $all_specs; do bundle exec rspec -f p --order defined $i > last.out; if [[ $? -ne 0 ]]; then cat last.out >> all.out; fi; done`; this copies output from each failed spec file to `all.out`;

"Hang on", you're saying, "we got a green bar at Step 5. What in the world are we doing with *~3,700 lines* of failed-spec output? Excellent question.

*My current understanding is* that when you run `bundle exec rspec` (or `bundle exec rake`, which runs the first command as a prerequisite), various RSpec setup and shared state occurs differently than when you run RSpec against a single spec file. 

"Right", you think, "so how do we get a list of just the files with failing specs?" That's what the `all.out` file is going to tell us. Run the command

```
ack ^rspec all.out | cut -f 1 -d ':' | awk '{printf("%s\n", $2);}' | sed 's,^./,,' | sort -u
```

and you'll get a list of 51 spec files that fail when running individually that *did not* fail when running the complete suite. (I think it's *entirely* reasonable to regard this as a mortal defect in the tool itself, since it claims that each example in each spec is set up individually, but that's beside the current point.) This tells us that a less-trusting, "belt-and-suspenders" approach is warranted.

For the record, the failing individual spec files are:


1. [`spec/controllers/posts_controller/action/create_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/action/create_spec.rb)
1. [`spec/controllers/posts_controller/responder/create_failure_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/create_failure_spec.rb)
1. [`spec/controllers/posts_controller/responder/edit_success_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/edit_success_spec.rb)
1. [`spec/controllers/posts_controller/responder/index_success_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/index_success_spec.rb)
1. [`spec/controllers/posts_controller/responder/new_success_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/new_success_spec.rb)
1. [`spec/controllers/posts_controller/responder/show_success_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/show_success_spec.rb)
1. [`spec/controllers/posts_controller/responder/update_failure_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/update_failure_spec.rb)
1. [`spec/controllers/posts_controller/responder/update_success_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller/responder/update_success_spec.rb)
1. [`spec/controllers/posts_controller_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/posts_controller_spec.rb)
1. [`spec/controllers/sessions_controller_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/sessions_controller_spec.rb)
1. [`spec/controllers/users_controller/action/create_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/users_controller/action/create_spec.rb)
1. [`spec/controllers/users_controller/action/update_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/users_controller/action/update_spec.rb)
1. [`spec/controllers/users_controller_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/controllers/users_controller_spec.rb)
1. [`spec/features/attempting_login_after_logging_in_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_login_after_logging_in_fails_spec.rb)
1. [`spec/features/attempting_login_invalid_credentials_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_login_invalid_credentials_fails_spec.rb)
1. [`spec/features/attempting_to_register_an_invalid_name_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_to_register_an_invalid_name_fails_spec.rb)
1. [`spec/features/attempting_to_register_same_name_twice_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_to_register_same_name_twice_fails_spec.rb)
1. [`spec/features/attempting_to_register_while_logged_in_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_to_register_while_logged_in_fails_spec.rb)
1. [`spec/features/attempting_to_update_post_invalid_data_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_to_update_post_invalid_data_fails_spec.rb)
1. [`spec/features/attempting_view_nonexistent_member_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/attempting_view_nonexistent_member_fails_spec.rb)
1. [`spec/features/draft_post_only_accessible_to_author_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/draft_post_only_accessible_to_author_spec.rb)
1. [`spec/features/guest_can_view_user_profile_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/guest_can_view_user_profile_spec.rb)
1. [`spec/features/guest_user_attempting_new_post_fails_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/guest_user_attempting_new_post_fails_spec.rb)
1. [`spec/features/guest_viewing_member_list_sees_no_active_highlight_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/guest_viewing_member_list_sees_no_active_highlight_spec.rb)
1. [`spec/features/member_can_create_draft_post_directly_navigate_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_create_draft_post_directly_navigate_spec.rb)
1. [`spec/features/member_can_create_draft_post_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_create_draft_post_spec.rb)
1. [`spec/features/member_can_create_draft_post_view_in_profile_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_create_draft_post_view_in_profile_spec.rb)
1. [`spec/features/member_can_create_valid_image_post_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_create_valid_image_post_spec.rb)
1. [`spec/features/member_can_create_valid_text_post_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_create_valid_text_post_spec.rb)
1. [`spec/features/member_can_edit_own_profile_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_edit_own_profile_page_spec.rb)
1. [`spec/features/member_can_enter_image_url_on_new_post_form_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_enter_image_url_on_new_post_form_spec.rb)
1. [`spec/features/member_can_publish_article_view_on_landing_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_publish_article_view_on_landing_page_spec.rb)
1. [`spec/features/member_can_publish_articles_view_on_profile_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_publish_articles_view_on_profile_spec.rb)
1. [`spec/features/member_can_publish_then_edit_article_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_publish_then_edit_article_spec.rb)
1. [`spec/features/member_can_view_other_member_profile_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_view_other_member_profile_spec.rb)
1. [`spec/features/member_can_view_own_profile_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_can_view_own_profile_page_spec.rb)
1. [`spec/features/member_cannot_create_post_without_title_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_cannot_create_post_without_title_spec.rb)
1. [`spec/features/member_viewing_member_list_sees_own_listing_highlighted_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/member_viewing_member_list_sees_own_listing_highlighted_spec.rb)
1. [`spec/features/new_post_form_has_correct_button_text_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/new_post_form_has_correct_button_text_spec.rb)
1. [`spec/features/new_post_form_status_defaults_draft_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/new_post_form_status_defaults_draft_spec.rb)
1. [`spec/features/new_user_can_sign_up_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/new_user_can_sign_up_spec.rb)
1. [`spec/features/only_author_can_view_draft_post_in_profile_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/only_author_can_view_draft_post_in_profile_spec.rb)
1. [`spec/features/post_only_editable_by_author_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/post_only_editable_by_author_spec.rb)
1. [`spec/features/user_can_log_in_and_out_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/user_can_log_in_and_out_spec.rb)
1. [`spec/features/user_can_view_article_from_landing_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/user_can_view_article_from_landing_page_spec.rb)
1. [`spec/features/user_can_view_author_profile_from_article_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/user_can_view_author_profile_from_article_page_spec.rb)
1. [`spec/features/user_can_view_landing_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/user_can_view_landing_page_spec.rb)
1. [`spec/features/user_can_view_member_list_page_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/user_can_view_member_list_page_spec.rb)
1. [`spec/features/user_cannot_be_updated_invalid_data_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/features/user_cannot_be_updated_invalid_data_spec.rb)
1. [`spec/helpers/posts_helper_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/helpers/posts_helper_spec.rb)
1. [`spec/helpers/users_helper_spec.rb`](https://github.com/jdickey/new_poc/blob/f76896b/spec/helpers/users_helper_spec.rb)

**Comment by jdickey** [comment]
The above has been opened as a separate issue (#269).

**Comment by jdickey** [comment]
Fixed #269 and merged #271; going to redo the branch and cherry-pick.

**Comment by alex-fedorov** [comment]
By the way, I have just tried `attire` + `contracts` - works as expected:

```ruby
class Widget
  include Contracts
  Contract String, { bar: Maybe[String], baz: Maybe[Num] } => nil
  attire 'foo, bar: nil, baz: 42'
end
```

`attire` wil define its `initialize` method, and `contracts` will auto-attach the decorator to it as expected. And just tried to run a bunch of `Widget.new(...)` in `irb` and it works as expected.

**Comment by alex-fedorov** [comment]
That is because for `contracts` it doesn't matter if you use `def` to define method, or you use some ruby metaprogramming. I'm actually using this all the time:

```ruby
class Person
  include Contracts

  # ...

  private

  Contract None => String
  attr_reader :name

  Contract None => Num
  attr_reader :age
end
```

**Comment by jdickey** [comment]
@alex-fedorov Thanks for the help (here and on the [related `contracts.ruby` issue I had opened](https://github.com/egonSchiele/contracts.ruby/issues/148); appreciated!

**Pull request closed without merging**
