### PR TITLE
Fixing Post entity migration breakage.

### PR DESCRIPTION
**Pull request by jdickey**
As per the "Again, priorities" list in [this comment](https://github.com/jdickey/new_poc/issues/240#issuecomment-93783853) on Issue #240.

What will count as merge-worthy success is a green bar from *all* (existing, updated and new) specs using either `Newpoc::Entity::Post` or `Entity::Post` as the post-entity class. Then, of course, we can kill off the old `Newpoc::Entity::Post` entirely and be left with one remaining "unbuilt" Gem to merge back. :disappointed_relieved:

### CODE REVIEW

**Comment by jdickey** [comment]
`PostFactory` works, and sends through all attributes from the DAO record to the `Post` entity. If you notice the way the [`whitelist` is constructed](https://github.com/jdickey/new_poc/blob/c39b7f2/app/entities/post.rb#L32-L38) in `Entity::Post#init_attributes`, I still think the different *types* of attributes (core, persistence, publication, ...) should be broken out in some fashion, but decidedly *not* with the rococo style that was employed in the first `post-entities` branch.

**Comment by jdickey** [comment]
Note the commit message for ffd1a33:

> The old `Newpoc::Entity::Post` gave back a Hash from its `#attributes` method; `Entity::Post` gives a value object (on which accessors such as `#title` may be called, or `#to_hash` will hand back a Hash of all attributes).

One bit that falls out from this is that, once we kill off `Newpoc::Entity::Post`, it may be worthwhile to go back and evaluate all the attribute-to-hash conversions in specs and use value-object methods instead where sensible.

**Comment by jdickey** [comment]
And we've discovered two new problems with `Entity::Post`.

### First Problem

In [`PostsController::Action::Create#validate_post_data`](https://github.com/jdickey/new_poc/blob/ffd1a3382402f0dbdb8a463754ce042482d77a73/app/controllers/posts_controller/action/create.rb#L65), we tell whoever's interested what broke by serialising the `@entity` to JSON and broadcasting that serialisation. With `Newpoc::Entity::Post`, for en entity with no title (and after calling `#valid?`), that serialisation would look like

```json
{"author_name":"Just Anybody","body":"A Body","image_url":null,"slug":null,"title":null,"pubdate":null,"created_at":null,"updated_at":null,"validation_context":null,"errors":{"title":["can't be blank"]}}
```

The recovery code could either pull the errors out of the JSON, or pull it back into a Hash and use those attributes to initialise a new (invalid) instance matching the original.

The JSON for the corresponding `Entity::Post` instance at that point would look like

```json
"attributes":{"attributes":{"body":"A Body","author_name":"Just Anybody"}},"validators":{"validators":{"author_name":{"author_name":"Just Anybody","errors":[]},"body":{"primary":"body","other":"image_url","main_attribute":"A Body","other_empty":true,"errors":[]},"image_url":{"primary":"image_url","other":"body","main_attribute":"","other_empty":false,"errors":[]},"title":{"title":null,"errors":[]},"image_url":{"primary":"image_url","other":"body","main_attribute":"","other_empty":false,"errors":[]},"title":{"title":null,"errors":[]}}}}
```

A pretty-print of the state of the `Entity::Post` would look like

```
=> #<Entity::Post:0x007fb047ef80b8
 @attributes=#<Entity::Post::AttributeContainer:0x007fb047f03a58 @attributes=#<#<Class:0x007fb047f03940>:0x007fb047f03670 @author_name="Just Anybody", @body="A Body">>,
 @validators=
  #<Entity::Post::ValidatorGrouping:0x007fb047f01b40
   @validators=
    {:author_name=>#<Entity::Post::Validators::AuthorName:0x007fb047f0bb40 @author_name="Just Anybody", @errors=[]>,
     :body=>#<Entity::Post::Validators::Body:0x007fb047f0baf0 @errors=[], @main_attribute="A Body", @other=:image_url, @other_empty=true, @primary=:body>,
     :image_url=>#<Entity::Post::Validators::ImageUrl:0x007fb047f0ba28 @errors=[], @main_attribute="", @other=:body, @other_empty=false, @primary=:image_url>,
     :title=>#<Entity::Post::Validators::Title:0x007fb047f0b960 @errors=[], @title=nil>}>>
```

The attributes (to recreate a new entity instance) are down in the `attributes` hash, and error information is...*distributed*.

#### Possible Solution

Implement a `#to_json` method on `Entity::Post` that returns a hash of the attributes and errors similar to what the default `#to_json` produces when handed a `Newpoc::Entity::Post` instance. You can argue that this is a "quick-hack-level solution", but I prefer to think of it as *information hiding*; you're telling the world exactly and only what it needs to know to handle the use cases where a JSON representation of the entity would be required &mdash; namely, serialisation of attributes and error information.

### Second Problem

While running down the earlier problem, I rediscovered another difference between the two entity implementations. The old entity uses an `ActiveModel::Errors` instance to hold its error data; the new one does its own validation and serialises error data in a form similar to but not compatible with with `ActiveModel::Errors#messages` — which is *not the same thing as* `#full_messages`.

For example, if `ActiveErrors#messages` were to return (reformatted for legibility):

```ruby
{
  title: ['must not have leading whitespace', 'must not have trailing whitespace']
}
```

calling `#full_messages` on the same instance would produce

```ruby
[
  'Title must not have leading whitespace',
  'Title must not have trailing whitespace'
]

and `Entity::Posts` equivalent error serialisation would be

```ruby
[
  { title: 'must not have leading whitespace' },
  { title: 'must not have trailing whitespace' }
]
```

Not the same thing at all here, either.

#### Proposed Solutions

There are a few different ways we could handle this. One would be to bite the bullet and reimplement the [`Entity::Post::ValidatorGrouping` class](https://github.com/jdickey/new_poc/blob/ffd1a3382402f0dbdb8a463754ce042482d77a73/app/entities/post/validator_grouping.rb) so that it maintains, and wraps, an instance of `ActiveModel::Errors` to support the subset of that API presently supported by the class.

Another would be to implement an `#errors` method on `Entity::Post` that would build such an instance on the fly, add the entries in the existing error serialisation to that, and return it. A different approach to encapsulation, and I could easily be swayed as to the relative merits between the two.

**Comment by jdickey** [comment]
"First Problem" above fixed with new `Entity::Post#to_json` method. Entirely too much time spent poking around with RubyMine 7.1, which has potential but still needs a bit of tweaking. When it works, the productivity boost is *awesome*, though.

**Comment by jdickey** [comment]
"Second Problem" above, fixed. `Post#errors` and `Post#to_json` now return what should be eminently useable values.

**Comment by jdickey** [comment]
Well, not *quite* done with `Entity::Post#to_json`.

In the old entity, attributes were serialised in the "top level" of the JSON-converted Hash, and errors were "just another attribute". The new entity serialises the attributes under an `:attributes` key. While there are good arguments to be made that this is "cleaner", we really ought to maintain API compatibility until we get rid of the old entity entirely, and *then* think about improvements.

**Comment by jdickey** [comment]
Hooking in our new `Responder::CreateFailure` class, we're confronted with the fact that, somewhere along the way, our `PostDao` class lost its `post_status` field (which was previously either `draft` or `public`).

The quick-hack fix would be to add a `post_status` field back to the DAO, with validations and so on. Bear in mind that the only reason this field *ever* existed was so that controller-related logic could figure out whether the value of the `pubdate` field should be cleared (for `draft`) or set (for `published`). On the one hand, you could easily argue that that's just fine even with our revamped domain/implementation separation; persistence is an implementation detail, one of many which is perfectly acceptable to be nuked and rebuilt if/when we take the domain logic (entities+actions) and host in a new environment (like RubyMotion, or a JSON-serving back end.

On the other hand, I remember coming across various blog posts (and ISTR even one section in a book) talking about setting up "virtual fields" on an ActiveRecord model; things that *work* like fields, but aren't real fields in the database record as persisted.

Is it worth the time to dig that out, relearn the techniques, and apply them now? Sitting here at close enough to midnight as makes no difference, with raging flu symptoms, I'd argue "no; but I *will* open an issue, and mark it `fixlater`, to replace the re-added database field with a virtual field". All opposed, speak now or vent on the issue once I open it.

**Comment by jdickey** [comment]
A couple of interesting things break when you swap in a `PostsController::Responder::EditSuccess` (which assigns a DAO to the `@post` ivar on the `PostsController` instance) instead of "just" assigning the *entity*.

Consider this code in [`PostsHelper#status_select_options`](https://github.com/jdickey/new_poc/blob/af913fe/app/helpers/posts_helper.rb#L26-L31):

```ruby
  def status_select_options(post)
    option_items = [%w(draft draft), %w(public public)]
    # `status` appears to be an existing ActiveRecord::Base field. :(
    current_status = post.draft? ? 'draft' : 'public'
    options_for_select option_items, current_status
  end
```

The `Post` *entity* has a `#draft?` method that, internally (and presently) toggles on the status of the `pubdate` attribute; if `pubdate` is `nil`, then it's a draft; if there's a publication date associated with the post, it obviously *isn't* a draft. The DAO has *absolutely no business whatever* explicitly recording redundant information (it's dependent on `pubdate`, remember).

There's another, closely related, bump: the forms used to create or edit posts use the above `status_select_options` function to populate values for a drop-down combo box which itself is used to select values for a field named `post_status`, whose *sole reason for existing* was to make it easy to work with that form; it has *no use whatever* outside the context of the data-entry UI.

What to do? Rails *by default* assumes that any field named in a view exists *as a field in the database record* associated with that form. We'd *like* to break that assumption, to avoid having two(!) completely redundant fields in every single `Post` database record; that just chews up more memory and storage space. We're back to the point where we're forced to decide between adding "virtual attributes" just to paper over visibly broken aspects of Rails' architecture (or lack thereof), and adding nearly useless, blatantly redundant fields to the database schema so those defects' "[we don't need no *stinking* quality](http://www.imdb.com/title/tt0040897/quotes?item=qt0356583)! Velocity is all that matters" psychopathy can be assuaged.

**Comment by jdickey** [comment]
Sometimes things are simpler than they appear; sometimes there are moving parts one is only dimly aware of until they attach themselves to one's private parts and go *boom*; sometimes you chase ephemeral ghosts of self-delusionary ideas down Byzantine networks of blind alleys punctuated with steep falls and IEDs. And sometimes, if you are *very* lucky and *extremely* patient, there is the satisfaction of seeing things work just the way they ought.

No, I'm not proud of my velocity. But, at least, the needle *moves*.

**Comment by jdickey** [comment]
When building out the `IndexSuccess` responder (and thus changing what the controllers assigns to `@posts` from an array of entities to an array of `PostDao` instances), we find that, sure enough, all the presentational crapola added to the entities was a mistake, and we're back to looking at something like [Draper](https://github.com/drapergem/draper) again. This is salutary on *multiple* levels.

**Comment by jdickey** [comment]
Right, then. We've now wiped *that* bit of egg off our face; we still have the question of why the `PostDao` helper module isn't being automatically loaded and what we're going to do about it in, e.g., [`PostsController#on_index_success`](https://github.com/jdickey/new_poc/blob/2aba9ce/app/controllers/posts_controller.rb#L87-L93).

It makes *no sense* to fight Rails and figure out what we need to do to turn on this example of its "convention over configuration" mess. All the helper function we're trying to use *does* is to build and call a command-pattern object we've stashed [elsewhere](https://github.com/jdickey/new_poc/blob/2aba9ce/app/decorations/posts/html_body_builder.rb). Instead, we've the [beginnings](https://github.com/jdickey/new_poc/blob/2aba9ce/app/helpers/post_dao_helper.rb) of what, rather than a conventional Rails helper (which isn't working as such), could instead be thought of as a "presentation extension" to the Post instances and, as such, loaded by the responder itself rather than our [current hack](https://github.com/jdickey/new_poc/blob/2aba9ce/app/controllers/posts_controller.rb#L87-L93).

Damn.

**Comment by jdickey** [comment]
Fine; we're back to a [one-liner](https://github.com/jdickey/new_poc/blob/d41234c/app/controllers/posts_controller.rb#L88) for [`PostsController#on_index_success`](https://github.com/jdickey/new_poc/blob/d41234c/app/controllers/posts_controller.rb#L87-L89).

Our conventions now stipulate that:

1. A `Presentation` module nested within a particular DAO class defines methods to be mixed into a DAO instance for it to support presentational logic analogous to Rails view helpers or Draper decorators;
1. Responder *methods on a controller* (such as [`PostsController#on_index_success`](https://github.com/jdickey/new_poc/blob/d41234c/app/controllers/posts_controller.rb#L87-L89) instantiate a correspondingly-named *Responder class instance* (such as [`PostsController::Responder::IndexSuccess`](https://github.com/jdickey/new_poc/blob/d41234c/app/controllers/posts_controller/responder/index_success.rb), passing their controller instance to the constructor, and returning the Responder instance's return value from its `#respond_to` method, to which is passed the controller method's sole parameter;
1. This allows us to resume the previous convention that a DAO (implementation model) is purely a "bag o' fields" with validations and data-oriented extensions like [`friendly_id`](https://github.com/norman/friendly_id), with *all* view/form/etc support logic moved to its corresponding Presentation module.

Thoughts?

**Comment by mitpaladin** [comment]
:) simple enough as conventions go

**Comment by jdickey** [comment]
Commit 36e3a6a does two main things for us:

1. It includes the first responder class for a `PostsController` action failure, [`PostsController::Responder::UpdateFailure`](https://github.com/jdickey/new_poc/blob/36e3a6a/app/controllers/posts_controller/responder/update_failure.rb); and
1. It's the first commit *not* marked '[skip ci]` that returns an instance of `Entity::Post` as the [`PostFactory.entity_class`](https://github.com/jdickey/new_poc/blob/36e3a6a/app/entity_factories/post_factory.rb#L26). :clap:

In principle, that means we've achieved the goal of this branch and can merge back into `master` whenever we wish. In practice, I'd prefer to finish the rest of the `PostController` failure-mode responder classes first, just to be sure.

**Pull request merged**
